#!/usr/bin/env python3
"""Export the Phase 3 JSONL package as an idempotent D1 SQL import."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from export_d1 import sql_value


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--chunks", type=Path, default=root / "output/phase3/chunks.jsonl")
    parser.add_argument("--documents", type=Path, default=root / "output/phase3/documents.jsonl")
    parser.add_argument("--out", type=Path, default=root / "output/cloud/d1-phase3.sql")
    args = parser.parse_args()
    documents = [json.loads(line) for line in args.documents.read_text(encoding="utf-8").splitlines()]
    count = 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", encoding="utf-8") as output:
        output.write("-- Generated by cloud/export_phase3_d1.py.\n")
        for document in documents:
            # search_chunks is an FTS table: exact field equality is reliable,
            # while LIKE/GLOB on the unindexed source_id column is not.
            output.write(f"DELETE FROM search_chunks WHERE title = {sql_value(document['title'])};\n")
        for document in documents:
            values = (
                document["id"], document["title"], document.get("title_en"), document["language"],
                document["source_type"], document["checksum"], document["corpus_version"], document["rights_policy"],
            )
            output.write("INSERT OR REPLACE INTO documents "
                         "(id,title,title_en,language,source_type,checksum,corpus_version,rights_policy) VALUES ("
                         + ",".join(sql_value(value) for value in values) + ");\n")
        with args.chunks.open(encoding="utf-8") as chunks:
            for line in chunks:
                row = json.loads(line)
                metadata = row["metadata"]
                document = next(item for item in documents if item["id"] == metadata["document_id"])
                values = (
                    row["id"], metadata["source_type"], document["title"], metadata["heading_path"],
                    metadata["page_start"], metadata["page_end"], metadata["language"], row["text"],
                )
                output.write("INSERT INTO search_chunks "
                             "(source_id,source_type,title,reference,pdf_page,pdf_page_end,language,text) VALUES ("
                             + ",".join(sql_value(value) for value in values) + ");\n")
                count += 1
    print(json.dumps({"documents": len(documents), "search_chunks": count, "output": str(args.out)}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
