#!/usr/bin/env python3
"""Export Phase 1 exact-lookup tables and the D1 keyword index as SQL."""

from __future__ import annotations

import argparse
import sqlite3
from pathlib import Path


TABLES = {
    "documents": ("id", "title", "title_en", "language", "source_type", "checksum", "corpus_version", "rights_policy"),
    "bible_verses": ("book_id", "chapter", "verse", "translation", "language", "book_name", "text", "source_id"),
    "footnotes": (
        "book_id", "chapter", "verse", "note_no", "translation", "language",
        "book_name", "heading_text", "text", "source_id",
    ),
    "topics": ("id", "references_json"),
    "topic_aliases": ("language", "alias", "topic_id"),
}


def sql_value(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def export(database: Path, destination: Path) -> dict[str, int]:
    source = sqlite3.connect(f"file:{database.resolve()}?mode=ro", uri=True)
    destination.parent.mkdir(parents=True, exist_ok=True)
    counts: dict[str, int] = {}
    with destination.open("w", encoding="utf-8") as output:
        output.write("-- Generated by cloud/export_d1.py. Exact-lookup data only.\n")
        for table, columns in TABLES.items():
            output.write(f"DELETE FROM {table};\n")
            rows = source.execute(f"SELECT {','.join(columns)} FROM {table}")
            count = 0
            for row in rows:
                values = ",".join(sql_value(value) for value in row)
                output.write(f"INSERT INTO {table} ({','.join(columns)}) VALUES ({values});\n")
                count += 1
            counts[table] = count
    source.close()
    return counts


def search_reference(row: sqlite3.Row) -> str:
    if row["source_type"] == "reference_book":
        return row["heading_path"] or row["title"]
    heading = (row["heading_path"] or row["title"]).replace(" > ", " ")
    return heading


def export_search(database: Path, destination: Path) -> int:
    source = sqlite3.connect(f"file:{database.resolve()}?mode=ro", uri=True)
    source.row_factory = sqlite3.Row
    destination.parent.mkdir(parents=True, exist_ok=True)
    rows = source.execute("""
        SELECT c.source_id,c.source_type,d.title,c.heading_path,c.page_start,c.page_end,c.language,c.text
        FROM chunks c JOIN documents d ON d.id=c.document_id
        ORDER BY c.source_type,c.source_id
    """)
    count = 0
    with destination.open("w", encoding="utf-8") as output:
        output.write("-- Generated by cloud/export_d1.py. D1 FTS5 keyword fallback.\n")
        output.write("DELETE FROM search_chunks;\n")
        for row in rows:
            values = (
                row["source_id"], row["source_type"], row["title"], search_reference(row),
                row["page_start"], row["page_end"], row["language"], row["text"],
            )
            output.write("INSERT INTO search_chunks "
                         "(source_id,source_type,title,reference,pdf_page,pdf_page_end,language,text) VALUES ("
                         + ",".join(sql_value(value) for value in values) + ");\n")
            count += 1
    source.close()
    return count


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", type=Path, default=root / "output/phase1/ecclesia_phase1.sqlite3")
    parser.add_argument("--out", type=Path, default=root / "output/cloud/d1-data.sql")
    parser.add_argument("--search-out", type=Path, default=root / "output/cloud/d1-search.sql")
    args = parser.parse_args()
    counts = export(args.db, args.out)
    assert counts == {"documents": 10, "bible_verses": 31218, "footnotes": 15793, "topics": 3, "topic_aliases": 23}, counts
    search_count = export_search(args.db, args.search_out)
    assert search_count == 31159, search_count
    print(args.out)
    print(counts)
    print(args.search_out)
    print({"search_chunks": search_count})
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
